menu:
- {name: 'university', url: '/university'}
- {name: 'cv', url: '/cv'}
- {name: 'science', url: '/science'}
- {name: 'literature', url: '/literatures'}
- {name: 'conversations', url: '/conversations'}
- {name: 'contact', url: '/contact'}

university:
- {name: 'Theoratical Physics 3', department: 'Physics', information: 'Classical Mechanics 2 and Electrodynamics 2', grade: 'In Progress', url: 'tp3'}
- {name: 'Experimental Physics 3', department: 'Physics', information: 'Electromagnetic Waves and Foundations of Quantum Physics', grade: 'In Progress', url: 'ep3'}
- {name: 'Mathematics 3', department: 'Maths', information: 'Vector Calculus and Partial Differential Equations', grade: 'In Progress', url: 'maths3'}
- {name: 'Laboratory 1', department: 'labs', information: 'General Physics', grade: 'In Progress', url: 'lab1'}
- {name: 'Physical Modelling', department: 'comp', information: 'Introduction to Computer-based Physical Modelling', grade: '1.0', url: 'comp1'}
- {name: 'Women in STEM', department: 'nelec', information: 'Non Physics Electives', grade: '1.3', url: 'nelec1'}
- {name: 'Theoratical Physics 2', department: 'Physics', information: 'Electrodynamics 1', grade: '2.7', url: 'tp2'}
- {name: 'Mathematics 2', department: 'Maths', information: 'Calculus of Functions of More Than One Variable', grade: '2.3', url: 'maths2'}
- {name: 'Chemistry', department: 'Chem', information: 'Introduction to Chemistry for Physics', grade: '2.3', url: 'chem1'}
- {name: 'Theoratical Physics 1', department: 'Physics', information: 'Classical Mechanics 1', grade: '2.3', url: 'tp1'}
- {name: 'Experimental Physics 1', department: 'Physics', information: 'Mechanics', grade: '2.3', url: 'ep1'}
- {name: 'Mathematics 1', department: 'Maths', information: 'Linear Algebra and Calculus of Functions of One Variable', grade: '1.7', url: 'maths1'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/Mirzokhid'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/mirzokhid-ganiev-8b7454289'}
- {icon: 'instagram', link: 'https://www.instagram.com/trainsisbetter/'}

contacts:
- {name: 'Mirzokhid Ganiev', title: '-', department: 'Physics', institution: 'Universität Leipzig', institution_address: '1 Main Street, Canada', phone: '', email: 'mirzokhidg@gmail.com', office: '', image: 'assets/img/contact.jpg'}

science:
- {name: 'Laboratory Reports (Labs)', image: 'lab_image', description: 'I really like data, analysis and over indulging in graphs and plots. Which is why I usually am very proud of my labs as I put in a lot of work and pride in them. You can explore my recent collection of lab work here, hope you enjoy!' , url: 'labs' }

literatures:
- {name: 'Narrative Novel Reviews', image: 'lit_image', description: 'If you want a short desciptive review of some of the books I have read', url: 'book'}
- {name: 'forgotton in the playground', image: 'playground_img', description: 'The window reflected the darkness engulfing the world around. The front door shattered through. The house...', url: 'playground'}
- {name: 'dead fish', image: 'dead_fish_img', description: 'dead fish, the fish is dead. the fish is dead, the head of the fish is dead. the head of the fish is not dead. the head is dead, it is alive, it is dead....', url: 'dead_fish'}

book:
- {name: 'The Sarah Book', author: 'Scott McClanahan', image: 'sarah_book'}

conversations:
- {name: 'Bizarre Evolution of Sloths; The ones who swam, hiked, dwelled, and now hang', image: 'convo_3/image_1', description: 'Sloths are unique and fascinating creatures who somehow survived as slow and tree-bearing creatures. Creatures where half of the population die in attempting to climb down from trees to use the bathroom. An odd circumstance when their ancestors were water swimming, ground burrowing, mountain[…]', url: 'convo_3'}
- {name: 'Understanding Museums', image: 'convo_2/image_1', description: 'The Museums of Interest: Louvre Museum – Paris, France. The British Museum – London, England Van Gogh Museum – Amsterdam, Netherlands Uffizi Gallery – Florence, Italy. National Museum of Fine Arts named after Gapar Aitiev – Bishkek, Kyrgyzstan. Analysis: The four museums I toured virtually and one physically have their unique traits that are uncommon […]', url: 'convo_2'}
- {name: 'Why can you buy a house in Detroit for 1 USD', image: 'convo_1/image_1', description: 'Detroit is the largest city within the US state of Michigan. Being located in the midwest, it is the home to one of the earliest lands awarded to the United States. The city itself was founded in 1837, being generally a white-centred populous and slowly becoming a hub for commerce and industry. It was the […]', url: 'convo_1'}

labs:
- {name: 'labs 2', description: 'Short description for PDF 1.', url: 'labs2.pdf'}
- {name: 'labs 3', description: 'Short description for PDF 1.', url: 'labs3.pdf'}
- {name: 'labs 4', description: 'Short description for PDF 1.', url: 'labs4.pdf'}
#- {name: 'labs 6', description: 'Short description for PDF 1.', url: 'labs6.pdf'}
